unstable_features = true

condense_wildcard_suffixes = true

error_on_line_overflow = true

fn_params_layout = "Compressed"
fn_single_line = true
format_generated_files = false

group_imports = "StdExternalCrate"
hex_literal_case = "Upper"

match_block_trailing_comma = true
max_width = 80

reorder_impl_items = true

trailing_semicolon = false

use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true

wrap_comments = true
